[package]
name = "physical_based_renderer"
version="0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = { version = "0.42.0"}
bitflags = { version = "1.3.2" }
lazy_static = "1.4.0"
gltf = "0.15"
gl33 = "0.2.1"
glutin = "0.26.0"
ash = "0.33.3+1.2.191"
winit = "0.25.0"

[profile.dev]
incremental = true